# Generated by Django 4.1.7 on 2023-02-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quontity',
            new_name='quantity',
        ),
    ]
